language: node_js
node_js:
  - v12.6.0
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  directories:
  - node_modules
script:
  - yarn install
  - yarn lint
  - yarn test --coverage
